In [15]:
library(ggplot2)
library(dplyr)
# Load the required libraries
library(ggpubr)
# load dplyr and tidyr library

library(tidyr)
#https://bioconductor.org/packages/release/bioc/vignettes/annotatr/inst/doc/annotatr-vignette.html

In [16]:
setwd("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/sRNA_deseq/sRNA_STAR_testing")

In [17]:
data <- read.csv("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/TEtranscriptCount_testing/all_featureCounts_TE_testing.tab", header=FALSE,sep='\t')
data

In [ ]:
 # Split name column into 
data <- data %>% separate(V1, c('V9', 'V10','V11','V12'), sep =" ")
data

Warning message:
“Expected 4 pieces. Additional pieces discarded in 10000 rows [1, 2, 3, 4, 5, 6,
7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].”

      V9          V10              V11              V12 V2
1     L1MdTf_II   LINE/L1          C57BL_6NJ#1#100      C57BL_6NJ#1#100
2     (A)n        Simple_repeat    C57BL_6NJ#1#100      C57BL_6NJ#1#100
3     B1_Mm       SINE/Alu         C57BL_6NJ#1#100      C57BL_6NJ#1#100
4     (AACA)n     Simple_repeat    C57BL_6NJ#1#100      C57BL_6NJ#1#100
5     (TTTGT)n    Simple_repeat    C57BL_6NJ#1#100      C57BL_6NJ#1#100
6     B1_Mm       SINE/Alu         C57BL_6NJ#1#100      C57BL_6NJ#1#100
7     (TTTGT)n    Simple_repeat    C57BL_6NJ#1#100      C57BL_6NJ#1#100
8     (T)n        Simple_repeat    C57BL_6NJ#1#100      C57BL_6NJ#1#100
9     (TTTG)n     Simple_repeat    C57BL_6NJ#1#100      C57BL_6NJ#1#100
10    B1_Mur2     SINE/Alu         C57BL_6NJ#1#100      C57BL_6NJ#1#100
11    B1F1        SINE/Alu         C57BL_6NJ#1#100      C57BL_6NJ#1#100
12    (CAAA)n     Simple_repeat    C57BL_6NJ#1#100      C57BL_6NJ#1#100
13    PB1D10      SINE/Alu         C57BL_6NJ#1#100      C57BL_6NJ#1#100
14    (GA)n       Simple_repeat    C57BL_6NJ#1#100      C57BL_6NJ#1#100
15    RLTR31D_MM  LTR/ERVK         C57BL_6NJ#1#100      C57BL_6NJ#1#100
16    GA-rich     Low_complexity   C57BL_6NJ#1#100      C57BL_6NJ#1#100
17    L1_Mur1     LINE/L1          C57BL_6NJ#1#100      C57BL_6NJ#1#100
18    RLTR45-int  LTR/ERVK         C57BL_6NJ#1#100      C57BL_6NJ#1#100
19    B1F1        SINE/Alu         C57BL_6NJ#1#100      C57BL_6NJ#1#100
20    ID_B1       SINE/B4          C57BL_6NJ#1#100      C57BL_6NJ#1#100
21    RLTR14-int  LTR/ERV1         C57BL_6NJ#1#100      C57BL_6NJ#1#100
22    (TATG)n     Simple_repeat    C57BL_6NJ#1#100      C57BL_6NJ#1#100
23    A-rich      Low_complexity   C57BL_6NJ#1#100      C57BL_6NJ#1#100
24    IAPLTR1a_Mm LTR/ERVK         C57BL_6NJ#1#100      C57BL_6NJ#1#100
25    IAPEz-int   LTR/ERVK         C57BL_6NJ#1#100      C57BL_6NJ#1#100
26    IAPEz-int   LTR/ERVK         C57BL_6NJ#1#100      C57BL_6NJ#1#100
27    IAPLTR1a_Mm LTR/ERVK         C57BL_6NJ#1#100      C57BL_6NJ#1#100
28    L1MdA_I     LINE/L1          C57BL_6NJ#1#101      C57BL_6NJ#1#101
29    L1MdTf_II   LINE/L1          C57BL_6NJ#1#101      C57BL_6NJ#1#101
30    (A)n        Simple_repeat    C57BL_6NJ#1#101      C57BL_6NJ#1#101
⋮     ⋮           ⋮                ⋮                ⋮   ⋮
9971  A-rich      Low_complexity   C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9972  B1_Mus1     SINE/Alu         C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9973  A-rich      Low_complexity   C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9974  RSINE1      SINE/B4          C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9975  B3A         SINE/B2          C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9976  (ATAA)n     Simple_repeat    C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9977  L1MdV_III   LINE/L1          C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9978  RLTR9D      LTR/ERVK         C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9979  L1MdV_III   LINE/L1          C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9980  MLT1A1      LTR/ERVL-MaLR    C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9981  Charlie1a   DNA/hAT-Charlie  C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9982  L1MdMus_I   LINE/L1          C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9983  L1MdFanc_I  LINE/L1          C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9984  (AAAT)n     Simple_repeat    C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9985  L1MdMus_I   LINE/L1          C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9986  B1_Mur2     SINE/Alu         C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9987  B4A         SINE/B4          C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9988  (ACAA)n     Simple_repeat    C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9989  PB1D7       SINE/Alu         C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9990  (TAGAT)n    Simple_repeat    C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9991  MLT1C2      LTR/ERVL-MaLR    C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9992  MER2        DNA/TcMar-Tigger C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9993  MLTR14      LTR/ERV1         C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9994  B1_Mur2     SINE/Alu         C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9995  RMER12      LTR/ERVK         C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9996  (TTG)n      Simple_repeat    C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9997  ORR1B1-int  LTR/ERVL-MaLR    C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9998  RMER15      LTR/ERVL         C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
9999  L1MC3       LINE/L1          C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
10000 (GTTT)n     Simple_repeat    C57BL_6NJ#1#chr1     C57BL_6NJ#1#chr1
      V3      V4      V5 V6   V7
1         1    2759   -  2759 0
2      2952    2989   +    38 0
3      2995    3123   +   129 0
4      3125    3152   +    28 0
5      3445    3466   +    22 0
6      3467    3609   -   143 0
7      3610    3623   +    14 0
8      3624    3663   +    40 0
9      7412    7439   +    28 0
10     7680    7776   +    97 0
11     7817    7908   +    92 0
12     7909    7944   +    36 0
13     8990    9082   -    93 0
14     9408    9432   +    25 0
15     9439    9513   +    75 0
16     9514    9616   +   103 0
17     9982   10574   +   593 0
18    11649   11789   -   141 0
19    12149   12183   -    35 0
20    12150   12204   -    55 0
21    12507   13137   +   631 0
22    13138   13169   +    32 0
23    14621   14658   +    38 0
24    15285   15618   +   334 0
25    15619   18259   +  2641 0
26    18252   21482   +  3231 0
27    21483   21816   +   334 0
28        1    1380   +  1380 0
29     1381    2373   +   993 0
30     2380    2421   +    42 0
⋮     ⋮       ⋮       ⋮  ⋮    ⋮
9971  1912431 1912449 +    19  0.00
9972  1912450 1912596 +   147  1.97
9973  1912597 1912619 +    23  0.00
9974  1912694 1912770 +    77  0.00
9975  1912788 1912930 +   143  0.00
9976  1912975 1913016 +    42  0.00
9977  1914391 1916453 -  2063 18.87
9978  1916454 1916859 -   406  0.85
9979  1916860 1917394 -   535  4.09
9980  1917783 1917993 +   211  0.00
9981  1918124 1918716 -   593  4.00
9982  1918869 1919730 -   862  8.56
9983  1919737 1920293 +   557  7.03
9984  1920294 1920348 +    55  0.00
9985  1920357 1921825 -  1469 28.75
9986  1922392 1922527 +   136  1.01
9987  1922547 1922627 +    81  0.00
9988  1922704 1922769 +    66  0.00
9989  1923142 1923247 +   106  0.00
9990  1923253 1923284 +    32  0.00
9991  1924230 1924586 -   357  0.00
9992  1924616 1924772 -   157  0.00
9993  1924836 1925308 +   473  0.00
9994  1925799 1925950 -   152  0.06
9995  1926042 1926180 -   139  0.07
9996  1926181 1926219 +    39  0.12
9997  1926253 1926301 -    49  3.82
9998  1929447 1929563 -   117  0.00
9999  1930316 1930477 +   162  0.00
10000 1930534 1930551 +    18  0.00
      V8
1     pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
2     pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
3     pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
4     pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
5     pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
6     pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
7     pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
8     pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9     pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
10    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
11    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
12    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
13    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
14    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
15    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
16    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
17    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
18    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
19    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
20    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
21    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
22    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
23    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
24    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
25    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
26    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
27    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
28    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
29    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
30    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
⋮     ⋮
9971  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9972  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9973  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9974  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9975  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9976  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9977  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9978  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9979  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9980  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9981  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9982  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9983  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9984  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9985  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9986  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9987  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9988  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9989  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9990  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9991  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9992  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9993  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9994  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9995  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9996  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9997  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9998  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9999  pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
10000 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts

In [ ]:
# Group by V8, V9, V10 and sum the V7 values
new_data <- data %>%
  group_by(V8, V9, V10) %>%
  summarise(summed_V7 = sum(V7, na.rm = TRUE)) %>%
  ungroup()
new_data
write.csv(new_data, "TE_testing_repeat.csv", row.names=FALSE)

`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.

     V8
1    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
2    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
3    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
4    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
5    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
6    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
7    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
8    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
9    pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
10   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
11   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
12   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
13   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
14   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
15   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
16   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
17   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
18   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
19   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
20   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
21   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
22   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
23   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
24   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
25   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
26   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
27   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
28   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
29   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
30   pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
⋮    ⋮
1012 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1013 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1014 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1015 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1016 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1017 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1018 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1019 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1020 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1021 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1022 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1023 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1024 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1025 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1026 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1027 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1028 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1029 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1030 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1031 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1032 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1033 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1034 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1035 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1036 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1037 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1038 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1039 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1040 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
1041 pacBio/C57BL_6NJ/C57BL_6NJ-12.5dpp.1_10_1500_3000.featureCounts
     V9             V10              summed_V7
1    (A)n           Simple_repeat    37.99
2    (AAAAAC)n      Simple_repeat     0.00
3    (AAAAAG)n      Simple_repeat     0.00
4    (AAAAC)n       Simple_repeat     0.10
5    (AAAACA)n      Simple_repeat     0.00
6    (AAAAG)n       Simple_repeat     0.00
7    (AAAAGA)n      Simple_repeat     0.00
8    (AAAAT)n       Simple_repeat     0.00
9    (AAAC)n        Simple_repeat     0.24
10   (AAACA)n       Simple_repeat     0.15
11   (AAACAA)n      Simple_repeat     0.00
12   (AAAG)n        Simple_repeat     0.00
13   (AAAGA)n       Simple_repeat     0.03
14   (AAAGAA)n      Simple_repeat     0.00
15   (AAAGG)n       Simple_repeat     0.00
16   (AAAT)n        Simple_repeat     0.00
17   (AAATA)n       Simple_repeat     0.00
18   (AAC)n         Simple_repeat     1.85
19   (AACA)n        Simple_repeat     0.12
20   (AACAA)n       Simple_repeat     0.00
21   (AACAAC)n      Simple_repeat     0.00
22   (AACACA)n      Simple_repeat     0.00
23   (AACC)n        Simple_repeat     0.00
24   (AACCA)n       Simple_repeat     0.00
25   (AACCCTAAA)n   Simple_repeat     0.00
26   (AACTTTT)n     Simple_repeat     0.83
27   (AAG)n         Simple_repeat     0.00
28   (AAGA)n        Simple_repeat     0.00
29   (AAGAA)n       Simple_repeat     0.00
30   (AAGAG)n       Simple_repeat     0.00
⋮    ⋮              ⋮                ⋮
1012 RMER4A         LTR/ERVK            0.10
1013 RMER4B         LTR/ERVK            0.56
1014 RMER5          LTR/ERV1            0.00
1015 RMER6A         LTR/ERVK            0.06
1016 RMER6B         LTR/ERVK            0.00
1017 RMER6BA        LTR/ERVK            0.00
1018 RMER6C         LTR/ERVK            0.00
1019 RMER6D         LTR/ERVK            0.00
1020 RNERVK23-int   LTR/ERVK            0.00
1021 RSINE1         SINE/B4             0.58
1022 RodERV21-int   LTR/ERV1           45.63
1023 SYNREP_MM      Satellite           0.00
1024 Tigger1        DNA/TcMar-Tigger    0.00
1025 Tigger17a      DNA/TcMar-Tigger    0.00
1026 Tigger5b_Glire DNA/TcMar-Tigger   20.00
1027 Tigger6a       DNA/TcMar-Tigger    0.00
1028 U3             snRNA               0.00
1029 U6             snRNA              35.91
1030 UCON26         DNA/hAT-Ac          0.00
1031 UCON28a        Unknown             0.00
1032 URR1A          DNA/hAT-Charlie     1.71
1033 URR1B          DNA/hAT-Charlie     0.74
1034 YREP_Mm        Unknown             0.00
1035 Zaphod         DNA/hAT-Tip100      0.00
1036 polypurine     Low_complexity      0.00
1037 tRNA-Gln-CAA_v tRNA             2207.25
1038 tRNA-Gly-GGA   tRNA                0.50
1039 tRNA-Lys-AAG   tRNA             1159.11
1040 tRNA-Pro-CCA   tRNA                0.00
1041 tRNA-Pro-CCY   tRNA               33.81