In [19]:
library(ggplot2)
library(dplyr)
# Load the required libraries
library(ggpubr)
# load dplyr and tidyr library

library(tidyr)
library(parallel)
library(future)
library(furrr)

In [20]:
setwd("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/sRNA_deseq/sRNA_STAR_testing")

In [21]:
data <- read.csv("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/STAR_uniqe_marker_strain_wise/fetureCountTE/all_unieq_TE_count.tab", header=FALSE,sep='\t')#, nrows = 10000)

In [22]:
data <- data %>% filter(V7 != 0) 
data <- data %>% separate(V1, c('V9', 'V10','V11','V12'), sep =" ") 
data

Warning message:
“Expected 4 pieces. Additional pieces discarded in 6159693 rows [1, 2, 3, 4, 5,
6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].”

        V9              V10           V11                V12 V2
1       IAPEz-int       LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
2       IAPEz-int       LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
3       ETnERV-int      LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
4       ERVB4_1C-LTR_Mm LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
5       ERVB4_1C-LTR_Mm LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
6       MTA_Mm          LTR/ERVL-MaLR 129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
7       L1MdV_I         LINE/L1       129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
8       MuRRS4-int      LTR/ERV1      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
9       IAPEz-int       LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
10      MTA_Mm          LTR/ERVL-MaLR 129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
11      L1MdV_III       LINE/L1       129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
12      IAPEz-int       LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
13      MTA_Mm          LTR/ERVL-MaLR 129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
14      IAPEz-int       LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
15      MTA_Mm          LTR/ERVL-MaLR 129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
16      IAPLTR1_Mm      LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
17      IAPEz-int       LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
18      IAPLTR1_Mm      LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
19      LTRIS2          LTR/ERV1      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
20      ETnERV-int      LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
21      L1MdTf_III      LINE/L1       129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
22      MTA_Mm          LTR/ERVL-MaLR 129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
23      MTA_Mm          LTR/ERVL-MaLR 129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
24      IAPEz-int       LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
25      MTA_Mm          LTR/ERVL-MaLR 129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
26      IAPEz-int       LTR/ERVK      129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
27      L1MdN_I         LINE/L1       129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
28      L1MdA_VII       LINE/L1       129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
29      L1MdTf_III      LINE/L1       129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
30      MTA_Mm          LTR/ERVL-MaLR 129S1_SvImJ#1#chr1     129S1_SvImJ#1#chr1
⋮       ⋮               ⋮             ⋮                  ⋮   ⋮
6159664 IAPEz-int       LTR/ERVK      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159665 B1_Mus2         SINE/Alu      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159666 IAPEz-int       LTR/ERVK      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159667 MT2_Mm          LTR/ERVL      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159668 MERVL-int       LTR/ERVL      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159669 MT2_Mm          LTR/ERVL      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159670 Lx3_Mus         LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159671 L1MdTf_III      LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159672 IAPLTR2_Mm      LTR/ERVK      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159673 Lx3_Mus         LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159674 MT2_Mm          LTR/ERVL      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159675 (TTCA)n         Simple_repeat WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159676 IAPEz-int       LTR/ERVK      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159677 IAPEY4_I        LTR/ERVK      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159678 IAPEz-int       LTR/ERVK      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159679 L1MdV_I         LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159680 ORR1A1          LTR/ERVL-MaLR WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159681 L1MdF_IV        LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159682 L1MdF_III       LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159683 L1MdMus_II      LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159684 IAPEz-int       LTR/ERVK      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159685 IAPEz-int       LTR/ERVK      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159686 IAPEz-int       LTR/ERVK      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159687 L1MdGf_I        LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159688 L1MdTf_II       LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159689 L1MdF_III       LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159690 L1MdV_I         LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159691 MT2C_Mm         LTR/ERVL      WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159692 L1MdA_III       LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
6159693 L1MdFanc_II     LINE/L1       WSB_EiJ#1#chrX         WSB_EiJ#1#chrX
        V3        V4        V5 V6   V7
1        365650    368926   -  3277 0.07
2        368926    370202   -  1277 3.91
3        494375    495642   +  1268 1.00
4        495643    495765   +   123 1.00
5        745218    745340   +   123 1.00
6       1073058   1074155   -  1098 0.12
7       1156491   1161566   -  5076 0.07
8       1443918   1444165   -   248 0.75
9       1574682   1579682   +  5001 0.68
10      2298063   2299229   +  1167 0.12
11      2755182   2756000   -   819 0.33
12      3629812   3632909   +  3098 0.07
13      3786168   3787266   -  1099 0.94
14      3891183   3896191   -  5009 0.07
15      4123615   4124710   -  1096 0.94
16      4493507   4493863   -   357 0.75
17      4493868   4498843   -  4976 0.12
18      4500257   4500613   -   357 0.75
19      4902986   4903517   -   532 0.05
20      4995712   4999803   -  4092 0.02
21      5044675   5049884   +  5210 0.01
22      5265405   5266557   -  1153 0.31
23      6172732   6173826   +  1095 2.77
24      6326885   6327644   -   760 0.07
25      6914762   6915478   +   717 0.04
26      6971904   6973134   -  1231 0.40
27      7513234   7516075   -  2842 0.11
28      9543850   9547519   -  3670 0.01
29      9566900   9567269   +   370 0.01
30      9722553   9723649   +  1097 1.06
⋮       ⋮         ⋮         ⋮  ⋮    ⋮
6159664 143320927 143322007 +  1081 0.02
6159665 143377087 143377226 -   140 0.03
6159666 143938110 143944492 -  6383 1.88
6159667 144014251 144014743 +   493 0.48
6159668 144014744 144020115 +  5372 2.51
6159669 144020230 144020722 +   493 0.37
6159670 144484380 144484906 +   527 0.01
6159671 144702651 144707824 +  5174 0.06
6159672 144794085 144794539 -   455 0.03
6159673 144865406 144866359 -   954 0.01
6159674 145087603 145087795 +   193 0.04
6159675 145552521 145552552 +    32 0.93
6159676 145638104 145638365 +   262 0.22
6159677 145638363 145638485 +   123 0.28
6159678 145638468 145641439 +  2972 0.74
6159679 145843836 145845607 +  1772 0.04
6159680 146133279 146135066 +  1788 0.17
6159681 146164110 146165005 +   896 0.02
6159682 146199385 146199960 -   576 0.03
6159683 146223038 146224028 -   991 0.01
6159684 146238233 146238935 +   703 0.07
6159685 146238947 146239582 +   636 0.86
6159686 146239582 146242855 +  3274 1.18
6159687 146325179 146331839 -  6661 0.02
6159688 146356912 146363948 -  7037 0.07
6159689 146451283 146451687 +   405 0.02
6159690 146610157 146610599 -   443 0.02
6159691 146779824 146780299 -   476 0.03
6159692 146873889 146874617 -   729 0.02
6159693 146997534 147000074 -  2541 0.43
        V8
1       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
2       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
3       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
4       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
5       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
6       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
7       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
8       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
9       129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
10      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
11      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
12      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
13      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
14      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
15      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
16      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
17      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
18      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
19      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
20      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
21      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
22      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
23      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
24      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
25      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
26      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
27      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
28      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
29      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
30      129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts
⋮       ⋮
6159664 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159665 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159666 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159667 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159668 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159669 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159670 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159671 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159672 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159673 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159674 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159675 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159676 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159677 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159678 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159679 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159680 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159681 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159682 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159683 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159684 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159685 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159686 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159687 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159688 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159689 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159690 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159691 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159692 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts
6159693 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts

In [23]:
 # Split name column into 
new_data <- data %>%
  group_by(V8, V9, V10) %>%
  summarise(summed_V7 = sum(V7, na.rm = TRUE)) %>%
  ungroup()
new_data

`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.

      V8                                                    V9
1     129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (A)n
2     129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (AAAC)n
3     129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (AAACC)n
4     129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (AAC)n
5     129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (AACCA)n
6     129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (AAGCC)n
7     129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (AATC)n
8     129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (ACAA)n
9     129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (ACAG)n
10    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (ACAT)n
11    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (ACCAA)n
12    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (AGAC)n
13    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (AGAT)n
14    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (AGGTCACAC)n
15    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (ATAG)n
16    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (ATC)n
17    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (ATCT)n
18    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CA)n
19    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CAAA)n
20    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CAAAC)n
21    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CAAGAA)n
22    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CAAGC)n
23    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CAGGCATCA)n
24    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CCAAA)n
25    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CCAAG)n
26    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CCT)n
27    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CCTTCC)n
28    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CTAT)n
29    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CTCTCTGG)n
30    129S1_SvImJ/129S1_SvImJ-12.5dpp.1-P12.5.featureCounts (CTCTCTTG)n
⋮     ⋮                                                     ⋮
73088 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER15-int
73089 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER16A2
73090 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER17A2
73091 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER17B
73092 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER17B2
73093 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER17C
73094 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER19B
73095 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER19B2
73096 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER19C
73097 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER1A
73098 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER1B
73099 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER1C
73100 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER2
73101 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER20B
73102 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER21B
73103 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER3D-int
73104 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER4B
73105 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RMER5
73106 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RSINE1
73107 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         RodERV21-int
73108 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         SSU-rRNA_Hsa
73109 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         Tigger15a
73110 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         Tigger16b
73111 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         U1
73112 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         U2
73113 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         U8
73114 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         URR1A
73115 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         URR1B
73116 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         tRNA-Tyr-TAC
73117 WSB_EiJ/WSB_EiJ-20.5dpp.3-P20.5.featureCounts         tRNA-Val-GTA
      V10               summed_V7
1     Simple_repeat     5.00
2     Simple_repeat     1.00
3     Simple_repeat     0.60
4     Simple_repeat     2.00
5     Simple_repeat     0.20
6     Simple_repeat     0.20
7     Simple_repeat     2.00
8     Simple_repeat     1.00
9     Simple_repeat     0.01
10    Simple_repeat     4.83
11    Simple_repeat     0.20
12    Simple_repeat     0.02
13    Simple_repeat     9.59
14    Simple_repeat     1.00
15    Simple_repeat     1.02
16    Simple_repeat     0.40
17    Simple_repeat     1.58
18    Simple_repeat     4.00
19    Simple_repeat     1.00
20    Simple_repeat     0.50
21    Simple_repeat     0.08
22    Simple_repeat     0.20
23    Simple_repeat     2.00
24    Simple_repeat     0.80
25    Simple_repeat     0.60
26    Simple_repeat     6.00
27    Simple_repeat     3.00
28    Simple_repeat     0.01
29    Simple_repeat     0.32
30    Simple_repeat     0.32
⋮     ⋮                 ⋮
73088 LTR/ERVL          1831.00
73089 LTR/ERVK             0.12
73090 LTR/ERVK           198.00
73091 LTR/ERVK            49.00
73092 LTR/ERVK            46.00
73093 LTR/ERVK            77.00
73094 LTR/ERVK            50.95
73095 LTR/ERVK            53.00
73096 LTR/ERVK            10.00
73097 Retroposon/L1-dep    4.00
73098 Retroposon/L1-dep   33.00
73099 Retroposon/L1-dep    3.00
73100 LTR/ERV1             3.00
73101 LTR/ERVK             8.00
73102 LTR/ERV1            11.00
73103 LTR/ERVK          1849.69
73104 LTR/ERVK             5.00
73105 LTR/ERV1            12.00
73106 SINE/B4            398.98
73107 LTR/ERV1            36.30
73108 rRNA                23.00
73109 DNA/TcMar-Tigger     5.00
73110 DNA/TcMar-Tigger     0.03
73111 snRNA                9.00
73112 snRNA               39.00
73113 snRNA               40.00
73114 DNA/hAT-Charlie     53.00
73115 DNA/hAT-Charlie     83.00
73116 tRNA                12.00
73117 tRNA                74.00

In [24]:


write.csv(new_data, "all_unieq_TE_repeat.csv", row.names=FALSE)