In [1]:
library(ggplot2)
library(dplyr)
# Load the required libraries
library(ggpubr)
# load dplyr and tidyr library

library(tidyr)
library(parallel)
library(future)
library(furrr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
setwd("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/analysis/sRNA_deseq/sRNA_STAR_testing")

In [3]:
data <- read.csv("/mnt/home3/miska/nm667/scratch/inProgress/mice_PiRNA/results/TEtranscriptCount_testing/all_featureCounts_TE_testing.tab", header=FALSE,sep='\t')
data

         V1
1        pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
2        L1MdTf_II LINE/L1 C57BL_6NJ#1#100  1-2759
3        (A)n Simple_repeat C57BL_6NJ#1#100  2952-2989
4        B1_Mm SINE/Alu C57BL_6NJ#1#100  2995-3123
5        (AACA)n Simple_repeat C57BL_6NJ#1#100  3125-3152
6        (TTTGT)n Simple_repeat C57BL_6NJ#1#100  3445-3466
7        B1_Mm SINE/Alu C57BL_6NJ#1#100  3467-3609
8        (TTTGT)n Simple_repeat C57BL_6NJ#1#100  3610-3623
9        (T)n Simple_repeat C57BL_6NJ#1#100  3624-3663
10       (TTTG)n Simple_repeat C57BL_6NJ#1#100  7412-7439
11       B1_Mur2 SINE/Alu C57BL_6NJ#1#100  7680-7776
12       B1F1 SINE/Alu C57BL_6NJ#1#100  7817-7908
13       (CAAA)n Simple_repeat C57BL_6NJ#1#100  7909-7944
14       PB1D10 SINE/Alu C57BL_6NJ#1#100  8990-9082
15       (GA)n Simple_repeat C57BL_6NJ#1#100  9408-9432
16       RLTR31D_MM LTR/ERVK C57BL_6NJ#1#100  9439-9513
17       GA-rich Low_complexity C57BL_6NJ#1#100  9514-9616
18       L1_Mur1 LINE/L1 C57BL_6NJ#1#100  9982-10574
19       RLTR45-int LTR/ERVK C57BL_6NJ#1#100  11649-11789
20       B1F1 SINE/Alu C57BL_6NJ#1#100  12149-12183
21       ID_B1 SINE/B4 C57BL_6NJ#1#100  12150-12204
22       RLTR14-int LTR/ERV1 C57BL_6NJ#1#100  12507-13137
23       (TATG)n Simple_repeat C57BL_6NJ#1#100  13138-13169
24       A-rich Low_complexity C57BL_6NJ#1#100  14621-14658
25       IAPLTR1a_Mm LTR/ERVK C57BL_6NJ#1#100  15285-15618
26       IAPEz-int LTR/ERVK C57BL_6NJ#1#100  15619-18259
27       IAPEz-int LTR/ERVK C57BL_6NJ#1#100  18252-21482
28       IAPLTR1a_Mm LTR/ERVK C57BL_6NJ#1#100  21483-21816
29       L1MdA_I LINE/L1 C57BL_6NJ#1#101  1-1380
30       L1MdTf_II LINE/L1 C57BL_6NJ#1#101  1381-2373
⋮        ⋮
28770871 A-rich Low_complexity C57BL_6NJ#1#chrX  146375856-146375885
28770872 (AG)n Simple_repeat C57BL_6NJ#1#chrX  146375886-146375919
28770873 (TG)n Simple_repeat C57BL_6NJ#1#chrX  146375920-146375946
28770874 RMER10A LTR/ERVL C57BL_6NJ#1#chrX  146376164-146376597
28770875 (CA)n Simple_repeat C57BL_6NJ#1#chrX  146377412-146377439
28770876 RLTR20A4 LTR/ERVK C57BL_6NJ#1#chrX  146377905-146377974
28770877 (AC)n Simple_repeat C57BL_6NJ#1#chrX  146378571-146378606
28770878 (CA)n Simple_repeat C57BL_6NJ#1#chrX  146378611-146378652
28770879 L1_Rod LINE/L1 C57BL_6NJ#1#chrX  146380065-146380167
28770880 (AC)n Simple_repeat C57BL_6NJ#1#chrX  146380168-146380234
28770881 L1_Rod LINE/L1 C57BL_6NJ#1#chrX  146380235-146380470
28770882 L1MdF_V LINE/L1 C57BL_6NJ#1#chrX  146380477-146380739
28770883 L1MdF_IV LINE/L1 C57BL_6NJ#1#chrX  146380742-146380771
28770884 L1MdF_V LINE/L1 C57BL_6NJ#1#chrX  146380776-146380918
28770885 L1MA7 LINE/L1 C57BL_6NJ#1#chrX  146381542-146381818
28770886 MLT1D LTR/ERVL-MaLR C57BL_6NJ#1#chrX  146381829-146382251
28770887 (TTA)n Simple_repeat C57BL_6NJ#1#chrX  146383448-146383478
28770888 (TCCT)n Simple_repeat C57BL_6NJ#1#chrX  146384655-146384703
28770889 (T)n Simple_repeat C57BL_6NJ#1#chrX  146385105-146385130
28770890 L1MB8 LINE/L1 C57BL_6NJ#1#chrX  146386636-146386780
28770891 (ACGAA)n Simple_repeat C57BL_6NJ#1#chrX  146387030-146387066
28770892 MER58A DNA/hAT-Charlie C57BL_6NJ#1#chrX  146388446-146388631
28770893 B2_Mm1a SINE/B2 C57BL_6NJ#1#chrX  146389404-146389594
28770894 (T)n Simple_repeat C57BL_6NJ#1#chrX  146390876-146390892
28770895 (TCTG)n Simple_repeat C57BL_6NJ#1#chrX  146391519-146391534
28770896 (TGTCCATC)n Simple_repeat C57BL_6NJ#1#chrX  146391535-146391577
28770897 (TCTG)n Simple_repeat C57BL_6NJ#1#chrX  146391578-146391641
28770898 (TCTGTCCA)n Simple_repeat C57BL_6NJ#1#chrX  146391642-146391707
28770899 (TCTG)n Simple_repeat C57BL_6NJ#1#chrX  146391708-146391967
28770900 (G)n Simple_repeat C57BL_6NJ#1#chrX  146394220-146394240
         V2               V3        V4        V5 V6   V7
1                            NA        NA          NA NA
2        C57BL_6NJ#1#100      1      2759     -  2759  0
3        C57BL_6NJ#1#100   2952      2989     +    38  0
4        C57BL_6NJ#1#100   2995      3123     +   129  0
5        C57BL_6NJ#1#100   3125      3152     +    28  0
6        C57BL_6NJ#1#100   3445      3466     +    22  0
7        C57BL_6NJ#1#100   3467      3609     -   143  0
8        C57BL_6NJ#1#100   3610      3623     +    14  0
9        C57BL_6NJ#1#100   3624      3663     +    40  0
10       C57BL_6NJ#1#100   7412      7439     +    28  0
11       C57BL_6NJ#1#100   7680      7776     +    97  0
12       C57BL_6NJ#1#100   7817      7908     +    92  0
13       C57BL_6NJ#1#100   7909      7944     +    36  0
14       C57BL_6NJ#1#100   8990      9082     -    93  0
15       C57BL_6NJ#1#100   9408      9432     +    25  0
16       C57BL_6NJ#1#100   9439      9513     +    75  0
17       C57BL_6NJ#1#100   9514      9616     +   103  0
18       C57BL_6NJ#1#100   9982     10574     +   593  0
19       C57BL_6NJ#1#100  11649     11789     -   141  0
20       C57BL_6NJ#1#100  12149     12183     -    35  0
21       C57BL_6NJ#1#100  12150     12204     -    55  0
22       C57BL_6NJ#1#100  12507     13137     +   631  0
23       C57BL_6NJ#1#100  13138     13169     +    32  0
24       C57BL_6NJ#1#100  14621     14658     +    38  0
25       C57BL_6NJ#1#100  15285     15618     +   334  0
26       C57BL_6NJ#1#100  15619     18259     +  2641  0
27       C57BL_6NJ#1#100  18252     21482     +  3231  0
28       C57BL_6NJ#1#100  21483     21816     +   334  0
29       C57BL_6NJ#1#101      1      1380     +  1380  0
30       C57BL_6NJ#1#101   1381      2373     +   993  0
⋮        ⋮                ⋮         ⋮         ⋮  ⋮    ⋮
28770871 C57BL_6NJ#1#chrX 146375856 146375885 +   30   0.00
28770872 C57BL_6NJ#1#chrX 146375886 146375919 +   34   0.00
28770873 C57BL_6NJ#1#chrX 146375920 146375946 +   27   0.00
28770874 C57BL_6NJ#1#chrX 146376164 146376597 +  434   0.00
28770875 C57BL_6NJ#1#chrX 146377412 146377439 +   28   0.00
28770876 C57BL_6NJ#1#chrX 146377905 146377974 +   70   0.00
28770877 C57BL_6NJ#1#chrX 146378571 146378606 +   36   0.00
28770878 C57BL_6NJ#1#chrX 146378611 146378652 +   42   0.00
28770879 C57BL_6NJ#1#chrX 146380065 146380167 +  103   0.00
28770880 C57BL_6NJ#1#chrX 146380168 146380234 +   67   1.50
28770881 C57BL_6NJ#1#chrX 146380235 146380470 +  236   0.50
28770882 C57BL_6NJ#1#chrX 146380477 146380739 -  263   4.59
28770883 C57BL_6NJ#1#chrX 146380742 146380771 -   30   4.00
28770884 C57BL_6NJ#1#chrX 146380776 146380918 +  143   4.27
28770885 C57BL_6NJ#1#chrX 146381542 146381818 -  277   0.00
28770886 C57BL_6NJ#1#chrX 146381829 146382251 -  423   3.00
28770887 C57BL_6NJ#1#chrX 146383448 146383478 +   31   0.00
28770888 C57BL_6NJ#1#chrX 146384655 146384703 +   49   0.00
28770889 C57BL_6NJ#1#chrX 146385105 146385130 +   26   0.00
28770890 C57BL_6NJ#1#chrX 146386636 146386780 -  145  10.00
28770891 C57BL_6NJ#1#chrX 146387030 146387066 +   37   0.00
28770892 C57BL_6NJ#1#chrX 146388446 146388631 +  186  14.00
28770893 C57BL_6NJ#1#chrX 146389404 146389594 -  191  33.14
28770894 C57BL_6NJ#1#chrX 146390876 146390892 +   17   0.00
28770895 C57BL_6NJ#1#chrX 146391519 146391534 +   16   0.00
28770896 C57BL_6NJ#1#chrX 146391535 146391577 +   43   0.00
28770897 C57BL_6NJ#1#chrX 146391578 146391641 +   64   1.50
28770898 C57BL_6NJ#1#chrX 146391642 146391707 +   66   0.00
28770899 C57BL_6NJ#1#chrX 146391708 146391967 +  260   3.50
28770900 C57BL_6NJ#1#chrX 146394220 146394240 +   21   0.00
         V8
1
2        pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
3        pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
4        pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
5        pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
6        pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
7        pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
8        pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
9        pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
10       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
11       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
12       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
13       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
14       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
15       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
16       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
17       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
18       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
19       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
20       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
21       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
22       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
23       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
24       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
25       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
26       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
27       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
28       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
29       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
30       pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
⋮        ⋮
28770871 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770872 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770873 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770874 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770875 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770876 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770877 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770878 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770879 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770880 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770881 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770882 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770883 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770884 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770885 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770886 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770887 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770888 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770889 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770890 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770891 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770892 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770893 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770894 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770895 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770896 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770897 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770898 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770899 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
28770900 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts

In [4]:
 # Split name column into 
#data <- data %>% separate(V1, c('V9', 'V10','V11','V12'), sep =" ")
#data

split_name <- function(row) {
    separate(row, V1, c('V9', 'V10', 'V11', 'V12'), sep = " ")
}

# Determine the number of cores to use
num_cores <- 10

# Split the data into chunks for each core
chunks <- split(data, cut(1:nrow(data), num_cores, labels = FALSE))

# Process in parallel
results <- mclapply(chunks, function(chunk) split_name(chunk), mc.cores = num_cores)

# Combine results back together
data <- bind_rows(results)

In [5]:
# Group by V8, V9, V10 and sum the V7 values
#new_data <- data %>%
#  group_by(V8, V9, V10) %>%
#  summarise(summed_V7 = sum(V7, na.rm = TRUE)) %>%
#  ungroup()
#new_data
# Use multicore processing if on Unix/Linux, or multiprocess (which is sequential) if on Windows
plan(multicore)
# Split the data into chunks (for this example, let's say 4 chunks)
chunks <- split(data, cut(1:nrow(data), 150, labels = FALSE))

# Process each chunk in parallel
results <- future_map_dfr(chunks, ~ .x %>%
    group_by(V8, V9, V10) %>%
    summarise(summed_V7 = sum(V7, na.rm = TRUE)) %>%
    ungroup())
new_data <- results %>%
  group_by(V8, V9, V10) %>%
  summarise(summed_V7 = sum(summed_V7, na.rm = TRUE)) %>%
  ungroup()
new_data
write.csv(new_data, "TE_testing_repeat.csv", row.names=FALSE)

`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'V8', 'V9'. You can override using the
`.groups` argument.

       V8
1
2
3
4
5
6
7      pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
8      pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
9      pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
10     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
11     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
12     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
13     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
14     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
15     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
16     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
17     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
18     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
19     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
20     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
21     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
22     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
23     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
24     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
25     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
26     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
27     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
28     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
29     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
30     pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
⋮      ⋮
111181 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111182 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111183 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111184 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111185 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111186 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111187 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111188 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111189 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111190 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111191 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111192 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111193 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111194 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111195 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111196 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111197 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111198 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111199 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111200 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111201 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111202 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111203 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111204 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111205 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111206 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111207 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111208 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111209 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
111210 pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
       V9
1      pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_100_200.featureCounts
2      pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_1500_3000.featureCounts
3      pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_200_400.featureCounts
4      pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_400_800.featureCounts
5      pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_50_100.featureCounts
6      pacBio/C57BL_6NJ/C57BL_6NJ-16.5dpc.1_0_800_1600.featureCounts
7      (A)n
8      (AA)n
9      (AAA)n
10     (AAAA)n
11     (AAAAAAA)n
12     (AAAAAAC)n
13     (AAAAAAG)n
14     (AAAAAAT)n
15     (AAAAAC)n
16     (AAAAACA)n
17     (AAAAACC)n
18     (AAAAACT)n
19     (AAAAAG)n
20     (AAAAAGA)n
21     (AAAAAGAT)n
22     (AAAAAGC)n
23     (AAAAAGG)n
24     (AAAAAGT)n
25     (AAAAAT)n
26     (AAAAATA)n
27     (AAAAATT)n
28     (AAAAC)n
29     (AAAACA)n
30     (AAAACAA)n
⋮      ⋮
111181 tRNA-His-CAY
111182 tRNA-Ile-ATA
111183 tRNA-Ile-ATC
111184 tRNA-Ile-ATT
111185 tRNA-Leu-CTA
111186 tRNA-Leu-CTG
111187 tRNA-Leu-CTY
111188 tRNA-Leu-TTA
111189 tRNA-Leu-TTG
111190 tRNA-Lys-AAA
111191 tRNA-Lys-AAG
111192 tRNA-Met
111193 tRNA-Met-i
111194 tRNA-Met_v
111195 tRNA-Phe-TTY
111196 tRNA-Pro-CCA
111197 tRNA-Pro-CCG
111198 tRNA-Pro-CCY
111199 tRNA-Ser-AGY
111200 tRNA-Ser-TCG
111201 tRNA-Ser-TCY
111202 tRNA-Thr-ACA
111203 tRNA-Thr-ACG
111204 tRNA-Thr-ACY
111205 tRNA-Trp-TGG
111206 tRNA-Tyr-TAC
111207 tRNA-Tyr-TAT
111208 tRNA-Val-GTA
111209 tRNA-Val-GTG
111210 tRNA-Val-GTY
       V10           summed_V7
1      NA               0.00
2      NA               0.00
3      NA               0.00
4      NA               0.00
5      NA               0.00
6      NA               0.00
7      Simple_repeat 7705.18
8      Simple_repeat    0.00
9      Simple_repeat    4.06
10     Simple_repeat    0.00
11     Simple_repeat    0.00
12     Simple_repeat   33.39
13     Simple_repeat    0.36
14     Simple_repeat    0.00
15     Simple_repeat  776.87
16     Simple_repeat  272.85
17     Simple_repeat    0.68
18     Simple_repeat    0.00
19     Simple_repeat   60.33
20     Simple_repeat    0.01
21     Simple_repeat    0.00
22     Simple_repeat    0.00
23     Simple_repeat    0.00
24     Simple_repeat    2.50
25     Simple_repeat    4.60
26     Simple_repeat    2.06
27     Simple_repeat    0.00
28     Simple_repeat 1226.47
29     Simple_repeat  120.32
30     Simple_repeat   56.75
⋮      ⋮             ⋮
111181 tRNA           37082.80
111182 tRNA            1752.16
111183 tRNA               0.00
111184 tRNA            5244.11
111185 tRNA           17536.83
111186 tRNA          175093.45
111187 tRNA           48534.57
111188 tRNA           23723.23
111189 tRNA           18075.31
111190 tRNA           48824.53
111191 tRNA          191408.81
111192 tRNA            1292.35
111193 tRNA           29299.99
111194 tRNA            3826.89
111195 tRNA           58911.71
111196 tRNA            8856.37
111197 tRNA            3576.66
111198 tRNA            6454.08
111199 tRNA           21685.67
111200 tRNA           12976.43
111201 tRNA          800833.52
111202 tRNA             826.62
111203 tRNA            1013.00
111204 tRNA             857.68
111205 tRNA            1130.01
111206 tRNA            9928.79
111207 tRNA              19.00
111208 tRNA           42845.03
111209 tRNA          890337.16
111210 tRNA          463412.91