In [5]:
###testing R in jyupter

In [3]:
library(purrr)
library(tidyverse)
library(edgeR)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ dplyr   1.0.9
✔ tibble  3.1.7     ✔ stringr 1.4.0
✔ tidyr   1.2.0     ✔ forcats 0.5.1
✔ readr   2.1.2

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Loading required package: limma

In [4]:
lfbl=function(pattern,level=1){
    if(!exists("lof")) lof=vector("character",0)
    temp=list.files(pattern=pattern,no..=T)
    if(!is.na(temp[1])) lof=c(lof,paste0(getwd(),"/",temp))
    if(level>0){
        dirf=list.dirs(full.names=F,recursive=F)
        for(i in dirf){
            setwd(i)
            lof=c(lof,lfbl(pattern,level-1))
            setwd("..")
        }
    }
    return(lof)
}

In [5]:
setwd("/lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/")
getwd()

[1] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount"

In [6]:
f_files = lfbl(pattern = '16.5dpc.[1-3].raw.count.gz$',level=0)
f_files

 [1] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-16.5dpc.1.raw.count.gz"
 [2] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-16.5dpc.2.raw.count.gz"
 [3] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-16.5dpc.3.raw.count.gz"
 [4] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-16.5dpc.1.raw.count.gz"
 [5] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-16.5dpc.2.raw.count.gz"
 [6] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-16.5dpc.3.raw.count.gz"
 [7] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-16.5dpc.1.raw.count.gz"
 [8] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-16.5dpc.2.raw.count.gz"
 [9] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/AKR_J-16.5dpc.3.raw.count.gz"
[10] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-16.5dpc.1.raw.count.gz"
[11] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-16.5dpc.2.raw.count.gz"
[12] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/BALB_cJ-16.5dpc.3.raw.count.gz"
[13] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-16.5dpc.1.raw.count.gz"
[14] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-16.5dpc.2.raw.count.gz"
[15] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C3H_HeJ-16.5dpc.3.raw.count.gz"
[16] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-16.5dpc.1.raw.count.gz"
[17] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-16.5dpc.2.raw.count.gz"
[18] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/C57BL_6NJ-16.5dpc.3.raw.count.gz"
[19] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-16.5dpc.1.raw.count.gz"
[20] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-16.5dpc.2.raw.count.gz"
[21] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CAST_EiJ-16.5dpc.3.raw.count.gz"
[22] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-16.5dpc.1.raw.count.gz"
[23] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-16.5dpc.2.raw.count.gz"
[24] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/CBA_J-16.5dpc.3.raw.count.gz"
[25] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-16.5dpc.1.raw.count.gz"
[26] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-16.5dpc.2.raw.count.gz"
[27] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/DBA_2J-16.5dpc.3.raw.count.gz"
[28] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-16.5dpc.1.raw.count.gz"
[29] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-16.5dpc.2.raw.count.gz"
[30] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/FVB_NJ-16.5dpc.3.raw.count.gz"
[31] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-16.5dpc.1.raw.count.gz"
[32] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-16.5dpc.2.raw.count.gz"
[33] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/LP_J-16.5dpc.3.raw.count.gz"
[34] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-16.5dpc.1.raw.count.gz"
[35] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-16.5dpc.2.raw.count.gz"
[36] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NOD_ShiLtJ-16.5dpc.3.raw.count.gz"
[37] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-16.5dpc.1.raw.count.gz"
[38] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-16.5dpc.2.raw.count.gz"
[39] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/NZO_HlLtJ-16.5dpc.3.raw.count.gz"
[40] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-16.5dpc.1.raw.count.gz"
[41] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-16.5dpc.2.raw.count.gz"
[42] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/PWK_PhJ-16.5dpc.3.raw.count.gz"
[43] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-16.5dpc.1.raw.count.gz"
[44] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-16.5dpc.2.raw.count.gz"
[45] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/SPRET_EiJ-16.5dpc.3.raw.count.gz"
[46] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-16.5dpc.1.raw.count.gz"
[47] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-16.5dpc.2.raw.count.gz"
[48] "/lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/WSB_EiJ-16.5dpc.3.raw.count.gz"

In [7]:

samplenames = tools::file_path_sans_ext(tools::file_path_sans_ext(tools::file_path_sans_ext(tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T)))))
samplenames

 [1] "129S1_SvImJ-16.5dpc" "129S1_SvImJ-16.5dpc" "129S1_SvImJ-16.5dpc"
 [4] "A_J-16.5dpc"         "A_J-16.5dpc"         "A_J-16.5dpc"
 [7] "AKR_J-16.5dpc"       "AKR_J-16.5dpc"       "AKR_J-16.5dpc"
[10] "BALB_cJ-16.5dpc"     "BALB_cJ-16.5dpc"     "BALB_cJ-16.5dpc"
[13] "C3H_HeJ-16.5dpc"     "C3H_HeJ-16.5dpc"     "C3H_HeJ-16.5dpc"
[16] "C57BL_6NJ-16.5dpc"   "C57BL_6NJ-16.5dpc"   "C57BL_6NJ-16.5dpc"
[19] "CAST_EiJ-16.5dpc"    "CAST_EiJ-16.5dpc"    "CAST_EiJ-16.5dpc"
[22] "CBA_J-16.5dpc"       "CBA_J-16.5dpc"       "CBA_J-16.5dpc"
[25] "DBA_2J-16.5dpc"      "DBA_2J-16.5dpc"      "DBA_2J-16.5dpc"
[28] "FVB_NJ-16.5dpc"      "FVB_NJ-16.5dpc"      "FVB_NJ-16.5dpc"
[31] "LP_J-16.5dpc"        "LP_J-16.5dpc"        "LP_J-16.5dpc"
[34] "NOD_ShiLtJ-16.5dpc"  "NOD_ShiLtJ-16.5dpc"  "NOD_ShiLtJ-16.5dpc"
[37] "NZO_HlLtJ-16.5dpc"   "NZO_HlLtJ-16.5dpc"   "NZO_HlLtJ-16.5dpc"
[40] "PWK_PhJ-16.5dpc"     "PWK_PhJ-16.5dpc"     "PWK_PhJ-16.5dpc"
[43] "SPRET_EiJ-16.5dpc"   "SPRET_EiJ-16.5dpc"   "SPRET_EiJ-16.5dpc"
[46] "WSB_EiJ-16.5dpc"     "WSB_EiJ-16.5dpc"     "WSB_EiJ-16.5dpc"

In [8]:

#list of sample names with replicates 
lables = tools::file_path_sans_ext(tools::file_path_sans_ext(tools::file_path_sans_ext(sub(".*/", "", f_files,perl = T))))

lables

 [1] "129S1_SvImJ-16.5dpc.1" "129S1_SvImJ-16.5dpc.2" "129S1_SvImJ-16.5dpc.3"
 [4] "A_J-16.5dpc.1"         "A_J-16.5dpc.2"         "A_J-16.5dpc.3"
 [7] "AKR_J-16.5dpc.1"       "AKR_J-16.5dpc.2"       "AKR_J-16.5dpc.3"
[10] "BALB_cJ-16.5dpc.1"     "BALB_cJ-16.5dpc.2"     "BALB_cJ-16.5dpc.3"
[13] "C3H_HeJ-16.5dpc.1"     "C3H_HeJ-16.5dpc.2"     "C3H_HeJ-16.5dpc.3"
[16] "C57BL_6NJ-16.5dpc.1"   "C57BL_6NJ-16.5dpc.2"   "C57BL_6NJ-16.5dpc.3"
[19] "CAST_EiJ-16.5dpc.1"    "CAST_EiJ-16.5dpc.2"    "CAST_EiJ-16.5dpc.3"
[22] "CBA_J-16.5dpc.1"       "CBA_J-16.5dpc.2"       "CBA_J-16.5dpc.3"
[25] "DBA_2J-16.5dpc.1"      "DBA_2J-16.5dpc.2"      "DBA_2J-16.5dpc.3"
[28] "FVB_NJ-16.5dpc.1"      "FVB_NJ-16.5dpc.2"      "FVB_NJ-16.5dpc.3"
[31] "LP_J-16.5dpc.1"        "LP_J-16.5dpc.2"        "LP_J-16.5dpc.3"
[34] "NOD_ShiLtJ-16.5dpc.1"  "NOD_ShiLtJ-16.5dpc.2"  "NOD_ShiLtJ-16.5dpc.3"
[37] "NZO_HlLtJ-16.5dpc.1"   "NZO_HlLtJ-16.5dpc.2"   "NZO_HlLtJ-16.5dpc.3"
[40] "PWK_PhJ-16.5dpc.1"     "PWK_PhJ-16.5dpc.2"     "PWK_PhJ-16.5dpc.3"
[43] "SPRET_EiJ-16.5dpc.1"   "SPRET_EiJ-16.5dpc.2"   "SPRET_EiJ-16.5dpc.3"
[46] "WSB_EiJ-16.5dpc.1"     "WSB_EiJ-16.5dpc.2"     "WSB_EiJ-16.5dpc.3"

In [12]:
	
df = readDGE(f_files, path=NULL, columns=c(1,3), group= samplenames, labels = lables,sep="\t" )

In [13]:
head(df)

An object of class "DGEList"
$samples
                                                                                                                                                   files
129S1_SvImJ-16.5dpc.1 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-16.5dpc.1.raw.count.gz
129S1_SvImJ-16.5dpc.2 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-16.5dpc.2.raw.count.gz
129S1_SvImJ-16.5dpc.3 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/129S1_SvImJ-16.5dpc.3.raw.count.gz
A_J-16.5dpc.1                 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-16.5dpc.1.raw.count.gz
A_J-16.5dpc.2                 /lustre/scratch123/hgi/mdt2/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/seqCount/A_J-16.5dpc.2.raw.count.gz
                                    group lib.size norm.factors
129S1_SvImJ-16.5dpc.1 129S1_SvImJ-16.5dpc 67224656            1
129S1_SvImJ-16.5dpc.2 129S1_SvImJ-16.5dpc 71846926            1
129S1_SvImJ-16.5dpc.3 129S1_SvImJ-16.5dpc 77609680            1
A_J-16.5dpc.1                 A_J-16.5dpc 60227006            1
A_J-16.5dpc.2                 A_J-16.5dpc 37105413            1
43 more rows ...

$counts
                                      Samples
Tags                                   129S1_SvImJ-16.5dpc.1
  GTAGTCGTGGCCGAGTGGTTAAGG                           1060948
  GGGGATGTAGCTCAGTGGTAGAG                             261986
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA                140948
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT                 135685
  GTTTCCGTAGTGTAGTGGTTATCA                            124558
  GGGGGTGTAGCTCAGTGGTAGAG                             107199
                                      Samples
Tags                                   129S1_SvImJ-16.5dpc.2
  GTAGTCGTGGCCGAGTGGTTAAGG                           1423707
  GGGGATGTAGCTCAGTGGTAGAG                             406812
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA                231474
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT                 525017
  GTTTCCGTAGTGTAGTGGTTATCA                            212274
  GGGGGTGTAGCTCAGTGGTAGAG                             150876
                                      Samples
Tags                                   129S1_SvImJ-16.5dpc.3 A_J-16.5dpc.1
  GTAGTCGTGGCCGAGTGGTTAAGG                           1106923       1458134
  GGGGATGTAGCTCAGTGGTAGAG                             262758        625170
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA                238478        383286
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT                 164160        642059
  GTTTCCGTAGTGTAGTGGTTATCA                             86653        310415
  GGGGGTGTAGCTCAGTGGTAGAG                              81291        269538
                                      Samples
Tags                                   A_J-16.5dpc.2 A_J-16.5dpc.3
  GTAGTCGTGGCCGAGTGGTTAAGG                    729762       1493548
  GGGGATGTAGCTCAGTGGTAGAG                     155249        293936
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA        166481        567602
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT          81928        353016
  GTTTCCGTAGTGTAGTGGTTATCA                     72431        161617
  GGGGGTGTAGCTCAGTGGTAGAG                      72437        107168
                                      Samples
Tags                                   AKR_J-16.5dpc.1 AKR_J-16.5dpc.2
  GTAGTCGTGGCCGAGTGGTTAAGG                      190558          323540
  GGGGATGTAGCTCAGTGGTAGAG                        38257          190765
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA          477692          184661
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT           132556          216497
  GTTTCCGTAGTGTAGTGGTTATCA                       34828          173812
  GGGGGTGTAGCTCAGTGGTAGAG                        15470           63342
                                      Samples
Tags                                   AKR_J-16.5dpc.3 BALB_cJ-16.5dpc.1
  GTAGTCGTGGCCGAGTGGTTAAGG                      892202           1622146
  GGGGATGTAGCTCAGTGGTAGAG                       371611            665965
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA          152621            919351
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT           181050           1339227
  GTTTCCGTAGTGTAGTGGTTATCA                      179771            576569
  GGGGGTGTAGCTCAGTGGTAGAG                       115808            211266
                                      Samples
Tags                                   BALB_cJ-16.5dpc.2 BALB_cJ-16.5dpc.3
  GTAGTCGTGGCCGAGTGGTTAAGG                        395797            343502
  GGGGATGTAGCTCAGTGGTAGAG                          79642            229389
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA             61373             78705
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT              83658            215970
  GTTTCCGTAGTGTAGTGGTTATCA                         83009            239611
  GGGGGTGTAGCTCAGTGGTAGAG                          33271             59484
                                      Samples
Tags                                   C3H_HeJ-16.5dpc.1 C3H_HeJ-16.5dpc.2
  GTAGTCGTGGCCGAGTGGTTAAGG                       4159131           1487853
  GGGGATGTAGCTCAGTGGTAGAG                        1696875            613558
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA            707517            364784
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT            2144113            553973
  GTTTCCGTAGTGTAGTGGTTATCA                       1108587            307881
  GGGGGTGTAGCTCAGTGGTAGAG                         673153            204244
                                      Samples
Tags                                   C3H_HeJ-16.5dpc.3 C57BL_6NJ-16.5dpc.1
  GTAGTCGTGGCCGAGTGGTTAAGG                        449730              652368
  GGGGATGTAGCTCAGTGGTAGAG                         329613              385709
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA            388386              145368
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT             335105             1086450
  GTTTCCGTAGTGTAGTGGTTATCA                        233272              866377
  GGGGGTGTAGCTCAGTGGTAGAG                          83750               95784
                                      Samples
Tags                                   C57BL_6NJ-16.5dpc.2 C57BL_6NJ-16.5dpc.3
  GTAGTCGTGGCCGAGTGGTTAAGG                          648361             2347394
  GGGGATGTAGCTCAGTGGTAGAG                           289736             1269216
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA              374312              675696
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT               949032             1481204
  GTTTCCGTAGTGTAGTGGTTATCA                          418078             1282159
  GGGGGTGTAGCTCAGTGGTAGAG                            59081              297680
                                      Samples
Tags                                   CAST_EiJ-16.5dpc.1 CAST_EiJ-16.5dpc.2
  GTAGTCGTGGCCGAGTGGTTAAGG                         787391            2746210
  GGGGATGTAGCTCAGTGGTAGAG                          648665            3982884
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA             550789             811303
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT              807319            6016952
  GTTTCCGTAGTGTAGTGGTTATCA                         398742            2207800
  GGGGGTGTAGCTCAGTGGTAGAG                          176257            1076937
                                      Samples
Tags                                   CAST_EiJ-16.5dpc.3 CBA_J-16.5dpc.1
  GTAGTCGTGGCCGAGTGGTTAAGG                         509476         3544499
  GGGGATGTAGCTCAGTGGTAGAG                          282582         2037268
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA             435080         3358114
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT              172938         2577156
  GTTTCCGTAGTGTAGTGGTTATCA                         178400         1048430
  GGGGGTGTAGCTCAGTGGTAGAG                           88030          653074
                                      Samples
Tags                                   CBA_J-16.5dpc.2 CBA_J-16.5dpc.3
  GTAGTCGTGGCCGAGTGGTTAAGG                      589336          608921
  GGGGATGTAGCTCAGTGGTAGAG                       442945          641667
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA          170974          325510
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT           234657          423493
  GTTTCCGTAGTGTAGTGGTTATCA                      228560          708351
  GGGGGTGTAGCTCAGTGGTAGAG                       148829          189250
                                      Samples
Tags                                   DBA_2J-16.5dpc.1 DBA_2J-16.5dpc.2
  GTAGTCGTGGCCGAGTGGTTAAGG                      1112943           322519
  GGGGATGTAGCTCAGTGGTAGAG                        308101           310184
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA           117672            50542
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT             94140           175867
  GTTTCCGTAGTGTAGTGGTTATCA                        68640           231300
  GGGGGTGTAGCTCAGTGGTAGAG                        118565           106865
                                      Samples
Tags                                   DBA_2J-16.5dpc.3 FVB_NJ-16.5dpc.1
  GTAGTCGTGGCCGAGTGGTTAAGG                      1433815           106750
  GGGGATGTAGCTCAGTGGTAGAG                        386481            49958
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA           830938            39978
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT            390644            20638
  GTTTCCGTAGTGTAGTGGTTATCA                       103365            55380
  GGGGGTGTAGCTCAGTGGTAGAG                        132088            15617
                                      Samples
Tags                                   FVB_NJ-16.5dpc.2 FVB_NJ-16.5dpc.3
  GTAGTCGTGGCCGAGTGGTTAAGG                       712834            81616
  GGGGATGTAGCTCAGTGGTAGAG                        195011            19072
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA           416903            66097
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT            319647            14128
  GTTTCCGTAGTGTAGTGGTTATCA                       129634            19318
  GGGGGTGTAGCTCAGTGGTAGAG                         54530             6254
                                      Samples
Tags                                   LP_J-16.5dpc.1 LP_J-16.5dpc.2
  GTAGTCGTGGCCGAGTGGTTAAGG                     174551         221613
  GGGGATGTAGCTCAGTGGTAGAG                       76992          94525
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA          27119          29437
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT           23540          26325
  GTTTCCGTAGTGTAGTGGTTATCA                      42254          40234
  GGGGGTGTAGCTCAGTGGTAGAG                       20185          25568
                                      Samples
Tags                                   LP_J-16.5dpc.3 NOD_ShiLtJ-16.5dpc.1
  GTAGTCGTGGCCGAGTGGTTAAGG                     138131               691771
  GGGGATGTAGCTCAGTGGTAGAG                      128925               267257
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA          17498                98034
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT           60856               144333
  GTTTCCGTAGTGTAGTGGTTATCA                     146167               124972
  GGGGGTGTAGCTCAGTGGTAGAG                       39354                68016
                                      Samples
Tags                                   NOD_ShiLtJ-16.5dpc.2
  GTAGTCGTGGCCGAGTGGTTAAGG                            16613
  GGGGATGTAGCTCAGTGGTAGAG                              5164
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA                15792
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT                  2769
  GTTTCCGTAGTGTAGTGGTTATCA                             3875
  GGGGGTGTAGCTCAGTGGTAGAG                              1417
                                      Samples
Tags                                   NOD_ShiLtJ-16.5dpc.3 NZO_HlLtJ-16.5dpc.1
  GTAGTCGTGGCCGAGTGGTTAAGG                           239373              449173
  GGGGATGTAGCTCAGTGGTAGAG                            115083              147929
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA                24179              143358
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT                 75321               79346
  GTTTCCGTAGTGTAGTGGTTATCA                            76224               83061
  GGGGGTGTAGCTCAGTGGTAGAG                             33528               44769
                                      Samples
Tags                                   NZO_HlLtJ-16.5dpc.2 NZO_HlLtJ-16.5dpc.3
  GTAGTCGTGGCCGAGTGGTTAAGG                          271338              216644
  GGGGATGTAGCTCAGTGGTAGAG                           321175              213844
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA               41845               23270
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT               147192              109862
  GTTTCCGTAGTGTAGTGGTTATCA                          238566              244764
  GGGGGTGTAGCTCAGTGGTAGAG                           102797               77046
                                      Samples
Tags                                   PWK_PhJ-16.5dpc.1 PWK_PhJ-16.5dpc.2
  GTAGTCGTGGCCGAGTGGTTAAGG                        585523           1592728
  GGGGATGTAGCTCAGTGGTAGAG                         316558            580428
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA             32682            141779
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT              89800            320179
  GTTTCCGTAGTGTAGTGGTTATCA                        229248            321920
  GGGGGTGTAGCTCAGTGGTAGAG                         111914            235131
                                      Samples
Tags                                   PWK_PhJ-16.5dpc.3 SPRET_EiJ-16.5dpc.1
  GTAGTCGTGGCCGAGTGGTTAAGG                       1743858             5858018
  GGGGATGTAGCTCAGTGGTAGAG                         667239             1626098
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA            142563              750452
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT             434660             3962326
  GTTTCCGTAGTGTAGTGGTTATCA                        338507             1991574
  GGGGGTGTAGCTCAGTGGTAGAG                         255211              498391
                                      Samples
Tags                                   SPRET_EiJ-16.5dpc.2 SPRET_EiJ-16.5dpc.3
  GTAGTCGTGGCCGAGTGGTTAAGG                         2141362             6544352
  GGGGATGTAGCTCAGTGGTAGAG                          1556886             1994514
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA             1428325             1685661
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT              4477724             5689996
  GTTTCCGTAGTGTAGTGGTTATCA                         2321370             1848702
  GGGGGTGTAGCTCAGTGGTAGAG                           537556              767669
                                      Samples
Tags                                   WSB_EiJ-16.5dpc.1 WSB_EiJ-16.5dpc.2
  GTAGTCGTGGCCGAGTGGTTAAGG                       3059855           6746342
  GGGGATGTAGCTCAGTGGTAGAG                        1315980           2162437
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA           1207908           3333277
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT            1916913           5167200
  GTTTCCGTAGTGTAGTGGTTATCA                       1192851           2087994
  GGGGGTGTAGCTCAGTGGTAGAG                         363780            701673
                                      Samples
Tags                                   WSB_EiJ-16.5dpc.3
  GTAGTCGTGGCCGAGTGGTTAAGG                       5972656
  GGGGATGTAGCTCAGTGGTAGAG                        2073214
  GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA           2229169
  GTCTACGGCCATACCACCCTGAACGCGCCCGATCT            4211013
  GTTTCCGTAGTGTAGTGGTTATCA                       1875618
  GGGGGTGTAGCTCAGTGGTAGAG                         612035

In [19]:
mircounts <- df$counts

In [20]:
dim(mircounts)

[1] 261852868        48

In [21]:
head(mircounts,n=100)

                                     129S1_SvImJ-16.5dpc.1
GTAGTCGTGGCCGAGTGGTTAAGG             1060948
GGGGATGTAGCTCAGTGGTAGAG               261986
GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA  140948
GTCTACGGCCATACCACCCTGAACGCGCCCGATCT   135685
GTTTCCGTAGTGTAGTGGTTATCA              124558
GGGGGTGTAGCTCAGTGGTAGAG               107199
GAGAAAGACATATAGGATATG                  89075
TAAAAAGACATAGACTAACAGACTGGCT           87233
TAGAGAACATCGACACAACAGTCAAAGAA          86490
CGACTCTTAGCGGTGGATCACTCGGCT            83207
GACTCTTAGCGGTGGATCACTCGGCT             76925
TACAGACACTAAGAGAACACAAATGCCAGC         67082
GTAGTCGTGGCCGAGTGGTTAAG                60769
TAAAAAGACATAGACTAACAGACTGGCTA          55421
TAGGAAATTAGTCTGAACAGGTGAGA             55411
TTGAATCTGTAGATTGCTTTTGGCAAGATA         54319
GGGGATGTAGCTCAGTGGTAGA                 52332
TCCAATCGCGCGGAACTCGAGACT               49375
GTAGTCGTGGCTGAGTGGTTAAGG               48645
GAGAAAGGCATATAGGATATG                  47379
TATTGAAATTGTCCCATGTATCCTATC            47286
TACAGACACTAAGAGAACACAAATGCC            47125
TGAATCTGTAGATTGCTTTTGGCAAGATA          46549
TAGTAAAGCTCAAAGCATACATTGCACCT          44036
TCAATTCTGAATATCTACGCACCAAATG           43703
GGTAGCGTGGCCGAGCGGTCTAAGG              43306
TAAAGGAAGGCCTATCAGAATTACACC            42799
GACTCTTAGCGGTGGATCACTCGGCTC            40229
GCATTGTGGTTCAGTGGTAGAATTCTCGCCTGCCA    38389
TCGAGACTGCGGTACATAGGGAAGCA             37335
⋮                                    ⋮
GCATTGGTGGTTCAGTGGTAGAATTCT          20442
TAATTTCCTAAGTTCGGCGGGTCTCGGACC       20025
TAAGAATCCTACTAACAGAAATCAAGAC         19872
TCTTAGATCGATGTGGTGCTC                19818
TAGGAAATTAGTCTGAACAGGTGAGAGG         19812
TAGACTGGACCAGAAAAGAAATTCCTCCC        19806
TAACAGACTGGCTACACAAACAGGACC          19617
TACTGATGGATCAAAAACTGGCATAGGT         19534
TAAGAATCCTACTAACAGAAATCAAGACC        19432
TGTAAGATCGAGAATTGACAAATGGGACC        19258
GGGGATGTAGCTCAGTGGTAG                19157
TAATATAAAATATCTTGGCGTGACTC           18723
TAACAGACTGGCTACACAAACAGGACCC         18677
TACTCAACAAAACTGGAAAACCTGGACGA        18267
GTGAGTAATATAGATACGATGTCTTCTG         18241
TAAACAGGCTGAGAAAGAAATTAGGGAA         18020
TAGAGAACATCGACACAACAGTCAAAGAAA       17886
TAGTAAAGCTCAAAGCACACATTGCACCTC       17824
TAGGAAAGAGATCTGGAACCATAGAT           17617
TAAAGAACTCAAGAAGGTGGACTTCAGA         17181
TGACTAGTTAGCACTTTACTTGGCGGCT         16801
CGTTTCCGGCTCGAAGGACCA                16751
AGAAAAGAAGCCCGTGACATTGTTACTC         16744
TGAAGAAACAGACTGGGAGAAAAAAGC          16646
CGATACGACTCTTAGCGGTGGATCACTCGGCT     16508
TAGAAACCCTAGGAAAGAGATCTGGAACC        16431
ACTTCTGATAGATTGCCCTGAATTTCATCC       16415
TGCCAGCTGAGTCGCCTGACACCCGC           16140
TGATTTGCATTTCCCTGATGATTAAGGAT        16012
TCCGGTAGAATATGTGCAGATTAAATA          15977
                                     129S1_SvImJ-16.5dpc.2
GTAGTCGTGGCCGAGTGGTTAAGG             1423707
GGGGATGTAGCTCAGTGGTAGAG               406812
GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA  231474
GTCTACGGCCATACCACCCTGAACGCGCCCGATCT   525017
GTTTCCGTAGTGTAGTGGTTATCA              212274
GGGGGTGTAGCTCAGTGGTAGAG               150876
GAGAAAGACATATAGGATATG                 129861
TAAAAAGACATAGACTAACAGACTGGCT           95898
TAGAGAACATCGACACAACAGTCAAAGAA          68055
CGACTCTTAGCGGTGGATCACTCGGCT           162855
GACTCTTAGCGGTGGATCACTCGGCT            147173
TACAGACACTAAGAGAACACAAATGCCAGC         47585
GTAGTCGTGGCCGAGTGGTTAAG                74111
TAAAAAGACATAGACTAACAGACTGGCTA          43374
TAGGAAATTAGTCTGAACAGGTGAGA             61596
TTGAATCTGTAGATTGCTTTTGGCAAGATA         54984
GGGGATGTAGCTCAGTGGTAGA                 89568
TCCAATCGCGCGGAACTCGAGACT               43355
GTAGTCGTGGCTGAGTGGTTAAGG               74594
GAGAAAGGCATATAGGATATG                  91456
TATTGAAATTGTCCCATGTATCCTATC            38669
TACAGACACTAAGAGAACACAAATGCC            51815
TGAATCTGTAGATTGCTTTTGGCAAGATA          42991
TAGTAAAGCTCAAAGCATACATTGCACCT          33767
TCAATTCTGAATATCTACGCACCAAATG           38962
GGTAGCGTGGCCGAGCGGTCTAAGG              36924
TAAAGGAAGGCCTATCAGAATTACACC            40524
GACTCTTAGCGGTGGATCACTCGGCTC            38472
GCATTGTGGTTCAGTGGTAGAATTCTCGCCTGCCA    52483
TCGAGACTGCGGTACATAGGGAAGCA             36285
⋮                                    ⋮
GCATTGGTGGTTCAGTGGTAGAATTCT          35884
TAATTTCCTAAGTTCGGCGGGTCTCGGACC       33056
TAAGAATCCTACTAACAGAAATCAAGAC         15320
TCTTAGATCGATGTGGTGCTC                39864
TAGGAAATTAGTCTGAACAGGTGAGAGG         21815
TAGACTGGACCAGAAAAGAAATTCCTCCC        16686
TAACAGACTGGCTACACAAACAGGACC          15309
TACTGATGGATCAAAAACTGGCATAGGT         17670
TAAGAATCCTACTAACAGAAATCAAGACC        13663
TGTAAGATCGAGAATTGACAAATGGGACC        27075
GGGGATGTAGCTCAGTGGTAG                30093
TAATATAAAATATCTTGGCGTGACTC           19599
TAACAGACTGGCTACACAAACAGGACCC         16789
TACTCAACAAAACTGGAAAACCTGGACGA        18965
GTGAGTAATATAGATACGATGTCTTCTG         18909
TAAACAGGCTGAGAAAGAAATTAGGGAA         19731
TAGAGAACATCGACACAACAGTCAAAGAAA       11236
TAGTAAAGCTCAAAGCACACATTGCACCTC       13018
TAGGAAAGAGATCTGGAACCATAGAT           18688
TAAAGAACTCAAGAAGGTGGACTTCAGA         16813
TGACTAGTTAGCACTTTACTTGGCGGCT         19558
CGTTTCCGGCTCGAAGGACCA                14947
AGAAAAGAAGCCCGTGACATTGTTACTC         14545
TGAAGAAACAGACTGGGAGAAAAAAGC          18476
CGATACGACTCTTAGCGGTGGATCACTCGGCT     46995
TAGAAACCCTAGGAAAGAGATCTGGAACC        16102
ACTTCTGATAGATTGCCCTGAATTTCATCC       16971
TGCCAGCTGAGTCGCCTGACACCCGC           16023
TGATTTGCATTTCCCTGATGATTAAGGAT        18167
TCCGGTAGAATATGTGCAGATTAAATA          14940
                                     129S1_SvImJ-16.5dpc.3 A_J-16.5dpc.1
GTAGTCGTGGCCGAGTGGTTAAGG             1106923               1458134
GGGGATGTAGCTCAGTGGTAGAG               262758                625170
GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA  238478                383286
GTCTACGGCCATACCACCCTGAACGCGCCCGATCT   164160                642059
GTTTCCGTAGTGTAGTGGTTATCA               86653                310415
GGGGGTGTAGCTCAGTGGTAGAG                81291                269538
GAGAAAGACATATAGGATATG                  71049                208775
TAAAAAGACATAGACTAACAGACTGGCT          106426                  4021
TAGAGAACATCGACACAACAGTCAAAGAA          74279                  1764
CGACTCTTAGCGGTGGATCACTCGGCT            68070                300685
GACTCTTAGCGGTGGATCACTCGGCT             60798                265024
TACAGACACTAAGAGAACACAAATGCCAGC         64464                  1712
GTAGTCGTGGCCGAGTGGTTAAG                74935                147423
TAAAAAGACATAGACTAACAGACTGGCTA          48452                  2020
TAGGAAATTAGTCTGAACAGGTGAGA             70468                 10063
TTGAATCTGTAGATTGCTTTTGGCAAGATA         62155                 10615
GGGGATGTAGCTCAGTGGTAGA                 61026                168332
TCCAATCGCGCGGAACTCGAGACT               55766                  1136
GTAGTCGTGGCTGAGTGGTTAAGG               56089                 60047
GAGAAAGGCATATAGGATATG                  38800                 98315
TATTGAAATTGTCCCATGTATCCTATC            43650                  1341
TACAGACACTAAGAGAACACAAATGCC            55890                   408
TGAATCTGTAGATTGCTTTTGGCAAGATA          49893                  5610
TAGTAAAGCTCAAAGCATACATTGCACCT          40417                   277
TCAATTCTGAATATCTACGCACCAAATG           41982                   617
GGTAGCGTGGCCGAGCGGTCTAAGG              26296                 43825
TAAAGGAAGGCCTATCAGAATTACACC            43248                   741
GACTCTTAGCGGTGGATCACTCGGCTC            44044                 61554
GCATTGTGGTTCAGTGGTAGAATTCTCGCCTGCCA    58198                 90110
TCGAGACTGCGGTACATAGGGAAGCA             37171                  1077
⋮                                    ⋮                     ⋮
GCATTGGTGGTTCAGTGGTAGAATTCT          15747                 55516
TAATTTCCTAAGTTCGGCGGGTCTCGGACC       31470                  7826
TAAGAATCCTACTAACAGAAATCAAGAC         16376                   265
TCTTAGATCGATGTGGTGCTC                48332                 58625
TAGGAAATTAGTCTGAACAGGTGAGAGG         23874                  8017
TAGACTGGACCAGAAAAGAAATTCCTCCC        20257                  1234
TAACAGACTGGCTACACAAACAGGACC          17855                   404
TACTGATGGATCAAAAACTGGCATAGGT         21230                 26682
TAAGAATCCTACTAACAGAAATCAAGACC        15600                   293
TGTAAGATCGAGAATTGACAAATGGGACC        32270                  2983
GGGGATGTAGCTCAGTGGTAG                22381                 48257
TAATATAAAATATCTTGGCGTGACTC           24474                  2038
TAACAGACTGGCTACACAAACAGGACCC         19187                   595
TACTCAACAAAACTGGAAAACCTGGACGA        28058                  1319
GTGAGTAATATAGATACGATGTCTTCTG         21102                 21355
TAAACAGGCTGAGAAAGAAATTAGGGAA         20316                  2192
TAGAGAACATCGACACAACAGTCAAAGAAA       12906                   441
TAGTAAAGCTCAAAGCACACATTGCACCTC       14757                  2154
TAGGAAAGAGATCTGGAACCATAGAT           20024                   422
TAAAGAACTCAAGAAGGTGGACTTCAGA         19406                   726
TGACTAGTTAGCACTTTACTTGGCGGCT         22302                 12542
CGTTTCCGGCTCGAAGGACCA                54797                 42954
AGAAAAGAAGCCCGTGACATTGTTACTC         18339                 30605
TGAAGAAACAGACTGGGAGAAAAAAGC          23149                 23096
CGATACGACTCTTAGCGGTGGATCACTCGGCT     13113                 65026
TAGAAACCCTAGGAAAGAGATCTGGAACC        18718                   429
ACTTCTGATAGATTGCCCTGAATTTCATCC       18905                 33733
TGCCAGCTGAGTCGCCTGACACCCGC           19498                   594
TGATTTGCATTTCCCTGATGATTAAGGAT        20142                  8498
TCCGGTAGAATATGTGCAGATTAAATA          17151                 47555
                                     A_J-16.5dpc.2 A_J-16.5dpc.3
GTAGTCGTGGCCGAGTGGTTAAGG             729762        1493548
GGGGATGTAGCTCAGTGGTAGAG              155249         293936
GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA 166481         567602
GTCTACGGCCATACCACCCTGAACGCGCCCGATCT   81928         353016
GTTTCCGTAGTGTAGTGGTTATCA              72431         161617
GGGGGTGTAGCTCAGTGGTAGAG               72437         107168
GAGAAAGACATATAGGATATG                 65729         132886
TAAAAAGACATAGACTAACAGACTGGCT           3466           6490
TAGAGAACATCGACACAACAGTCAAAGAA          1692           2585
CGACTCTTAGCGGTGGATCACTCGGCT           92325         160555
GACTCTTAGCGGTGGATCACTCGGCT            79072         131531
TACAGACACTAAGAGAACACAAATGCCAGC         1386           2856
GTAGTCGTGGCCGAGTGGTTAAG               55420         102529
TAAAAAGACATAGACTAACAGACTGGCTA          1754           2817
TAGGAAATTAGTCTGAACAGGTGAGA             6375          13552
TTGAATCTGTAGATTGCTTTTGGCAAGATA         6605          13824
GGGGATGTAGCTCAGTGGTAGA                29536          57088
TCCAATCGCGCGGAACTCGAGACT                715           1339
GTAGTCGTGGCTGAGTGGTTAAGG              36815          75013
GAGAAAGGCATATAGGATATG                 31803          36496
TATTGAAATTGTCCCATGTATCCTATC            1084           1992
TACAGACACTAAGAGAACACAAATGCC             394            754
TGAATCTGTAGATTGCTTTTGGCAAGATA          3989           7522
TAGTAAAGCTCAAAGCATACATTGCACCT           209            316
TCAATTCTGAATATCTACGCACCAAATG            559           1188
GGTAGCGTGGCCGAGCGGTCTAAGG             26938          44263
TAAAGGAAGGCCTATCAGAATTACACC             636           1156
GACTCTTAGCGGTGGATCACTCGGCTC           40468          84422
GCATTGTGGTTCAGTGGTAGAATTCTCGCCTGCCA   43173         121517
TCGAGACTGCGGTACATAGGGAAGCA              730           1402
⋮                                    ⋮             ⋮
GCATTGGTGGTTCAGTGGTAGAATTCT          13690         27836
TAATTTCCTAAGTTCGGCGGGTCTCGGACC        5644         11636
TAAGAATCCTACTAACAGAAATCAAGAC           258           408
TCTTAGATCGATGTGGTGCTC                28998         46557
TAGGAAATTAGTCTGAACAGGTGAGAGG          5425         11756
TAGACTGGACCAGAAAAGAAATTCCTCCC          931          1904
TAACAGACTGGCTACACAAACAGGACC            355           645
TACTGATGGATCAAAAACTGGCATAGGT         14808         28341
TAAGAATCCTACTAACAGAAATCAAGACC          326           537
TGTAAGATCGAGAATTGACAAATGGGACC         1766          5432
GGGGATGTAGCTCAGTGGTAG                10008         19420
TAATATAAAATATCTTGGCGTGACTC            1296          2868
TAACAGACTGGCTACACAAACAGGACCC           523          1000
TACTCAACAAAACTGGAAAACCTGGACGA          800          2045
GTGAGTAATATAGATACGATGTCTTCTG         14119         19772
TAAACAGGCTGAGAAAGAAATTAGGGAA          1376          2545
TAGAGAACATCGACACAACAGTCAAAGAAA         451           607
TAGTAAAGCTCAAAGCACACATTGCACCTC        1766          3324
TAGGAAAGAGATCTGGAACCATAGAT             384           725
TAAAGAACTCAAGAAGGTGGACTTCAGA           632          1207
TGACTAGTTAGCACTTTACTTGGCGGCT          8208         13086
CGTTTCCGGCTCGAAGGACCA                19079         70063
AGAAAAGAAGCCCGTGACATTGTTACTC         16565         30291
TGAAGAAACAGACTGGGAGAAAAAAGC          13013         31989
CGATACGACTCTTAGCGGTGGATCACTCGGCT     14723         30683
TAGAAACCCTAGGAAAGAGATCTGGAACC          293           779
ACTTCTGATAGATTGCCCTGAATTTCATCC       21481         45280
TGCCAGCTGAGTCGCCTGACACCCGC             518          1204
TGATTTGCATTTCCCTGATGATTAAGGAT         5137          8861
TCCGGTAGAATATGTGCAGATTAAATA          25914         41661
                                     AKR_J-16.5dpc.1 AKR_J-16.5dpc.2
GTAGTCGTGGCCGAGTGGTTAAGG             190558          323540
GGGGATGTAGCTCAGTGGTAGAG               38257          190765
GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA 477692          184661
GTCTACGGCCATACCACCCTGAACGCGCCCGATCT  132556          216497
GTTTCCGTAGTGTAGTGGTTATCA              34828          173812
GGGGGTGTAGCTCAGTGGTAGAG               15470           63342
GAGAAAGACATATAGGATATG                 11694           91534
TAAAAAGACATAGACTAACAGACTGGCT          45667           23866
TAGAGAACATCGACACAACAGTCAAAGAA         24168           11833
CGACTCTTAGCGGTGGATCACTCGGCT           35262           66409
GACTCTTAGCGGTGGATCACTCGGCT            17798           52584
TACAGACACTAAGAGAACACAAATGCCAGC        22483           15294
GTAGTCGTGGCCGAGTGGTTAAG               10125           77330
TAAAAAGACATAGACTAACAGACTGGCTA         19428            9633
TAGGAAATTAGTCTGAACAGGTGAGA            11006           20929
TTGAATCTGTAGATTGCTTTTGGCAAGATA        15471            8592
GGGGATGTAGCTCAGTGGTAGA                 7383           88563
TCCAATCGCGCGGAACTCGAGACT               2108           17405
GTAGTCGTGGCTGAGTGGTTAAGG               9013           10519
GAGAAAGGCATATAGGATATG                  6596           24300
TATTGAAATTGTCCCATGTATCCTATC            7908            6983
TACAGACACTAAGAGAACACAAATGCC           11210            7988
TGAATCTGTAGATTGCTTTTGGCAAGATA         18005           10351
TAGTAAAGCTCAAAGCATACATTGCACCT          9517            6193
TCAATTCTGAATATCTACGCACCAAATG          19798           13062
GGTAGCGTGGCCGAGCGGTCTAAGG              6588           10428
TAAAGGAAGGCCTATCAGAATTACACC           11234            8256
GACTCTTAGCGGTGGATCACTCGGCTC           32460           56979
GCATTGTGGTTCAGTGGTAGAATTCTCGCCTGCCA  103940           47126
TCGAGACTGCGGTACATAGGGAAGCA             8950           15543
⋮                                    ⋮               ⋮
GCATTGGTGGTTCAGTGGTAGAATTCT          23944           24399
TAATTTCCTAAGTTCGGCGGGTCTCGGACC       43285           12611
TAAGAATCCTACTAACAGAAATCAAGAC          4039            2322
TCTTAGATCGATGTGGTGCTC                 5840           45814
TAGGAAATTAGTCTGAACAGGTGAGAGG         25807           19843
TAGACTGGACCAGAAAAGAAATTCCTCCC         7826            5810
TAACAGACTGGCTACACAAACAGGACC           4322            4302
TACTGATGGATCAAAAACTGGCATAGGT         28101           27850
TAAGAATCCTACTAACAGAAATCAAGACC         5669            2846
TGTAAGATCGAGAATTGACAAATGGGACC        28463           23596
GGGGATGTAGCTCAGTGGTAG                 2133           16290
TAATATAAAATATCTTGGCGTGACTC           27572           26252
TAACAGACTGGCTACACAAACAGGACCC          7657            6027
TACTCAACAAAACTGGAAAACCTGGACGA         1902            1272
GTGAGTAATATAGATACGATGTCTTCTG         31553           16590
TAAACAGGCTGAGAAAGAAATTAGGGAA          9768            7020
TAGAGAACATCGACACAACAGTCAAAGAAA        5153            2267
TAGTAAAGCTCAAAGCACACATTGCACCTC        6406            4128
TAGGAAAGAGATCTGGAACCATAGAT            4765            5357
TAAAGAACTCAAGAAGGTGGACTTCAGA          8186            7124
TGACTAGTTAGCACTTTACTTGGCGGCT         29714           19952
CGTTTCCGGCTCGAAGGACCA                19739           70352
AGAAAAGAAGCCCGTGACATTGTTACTC         28573           28349
TGAAGAAACAGACTGGGAGAAAAAAGC          26111           25596
CGATACGACTCTTAGCGGTGGATCACTCGGCT      7228           11394
TAGAAACCCTAGGAAAGAGATCTGGAACC         6942            4353
ACTTCTGATAGATTGCCCTGAATTTCATCC       47839           29005
TGCCAGCTGAGTCGCCTGACACCCGC            3595            8430
TGATTTGCATTTCCCTGATGATTAAGGAT         9091            5295
TCCGGTAGAATATGTGCAGATTAAATA          37065           33908
                                     AKR_J-16.5dpc.3 BALB_cJ-16.5dpc.1 ⋯
GTAGTCGTGGCCGAGTGGTTAAGG             892202          1622146           ⋯
GGGGATGTAGCTCAGTGGTAGAG              371611           665965           ⋯
GCATTGGTGGTTCAGTGGTAGAATTCTCGCCTGCCA 152621           919351           ⋯
GTCTACGGCCATACCACCCTGAACGCGCCCGATCT  181050          1339227           ⋯
GTTTCCGTAGTGTAGTGGTTATCA             179771           576569           ⋯
GGGGGTGTAGCTCAGTGGTAGAG              115808           211266           ⋯
GAGAAAGACATATAGGATATG                137831           572983           ⋯
TAAAAAGACATAGACTAACAGACTGGCT          26007             3276           ⋯
TAGAGAACATCGACACAACAGTCAAAGAA         15374             1441           ⋯
CGACTCTTAGCGGTGGATCACTCGGCT          138066           357511           ⋯
GACTCTTAGCGGTGGATCACTCGGCT           110030           309313           ⋯
TACAGACACTAAGAGAACACAAATGCCAGC        12056             1303           ⋯
GTAGTCGTGGCCGAGTGGTTAAG              121207           219404           ⋯
TAAAAAGACATAGACTAACAGACTGGCTA         13593             2054           ⋯
TAGGAAATTAGTCTGAACAGGTGAGA            19106             2979           ⋯
TTGAATCTGTAGATTGCTTTTGGCAAGATA         9264             5381           ⋯
GGGGATGTAGCTCAGTGGTAGA                94816           116114           ⋯
TCCAATCGCGCGGAACTCGAGACT              14630              393           ⋯
GTAGTCGTGGCTGAGTGGTTAAGG              31195            92520           ⋯
GAGAAAGGCATATAGGATATG                 49470            81868           ⋯
TATTGAAATTGTCCCATGTATCCTATC            7373             1089           ⋯
TACAGACACTAAGAGAACACAAATGCC            7397              273           ⋯
TGAATCTGTAGATTGCTTTTGGCAAGATA         13101             3691           ⋯
TAGTAAAGCTCAAAGCATACATTGCACCT          7129              211           ⋯
TCAATTCTGAATATCTACGCACCAAATG          11366              446           ⋯
GGTAGCGTGGCCGAGCGGTCTAAGG             45627           177813           ⋯
TAAAGGAAGGCCTATCAGAATTACACC            9257              430           ⋯
GACTCTTAGCGGTGGATCACTCGGCTC           50815            51319           ⋯
GCATTGTGGTTCAGTGGTAGAATTCTCGCCTGCCA   43191           195980           ⋯
TCGAGACTGCGGTACATAGGGAAGCA            12994              245           ⋯
⋮                                    ⋮               ⋮                 ⋱
GCATTGGTGGTTCAGTGGTAGAATTCT          33949           131288            ⋯
TAATTTCCTAAGTTCGGCGGGTCTCGGACC       12030             8818            ⋯
TAAGAATCCTACTAACAGAAATCAAGAC          3764              323            ⋯
TCTTAGATCGATGTGGTGCTC                48630            15603            ⋯
TAGGAAATTAGTCTGAACAGGTGAGAGG         16431             7869            ⋯
TAGACTGGACCAGAAAAGAAATTCCTCCC         6104              744            ⋯
TAACAGACTGGCTACACAAACAGGACC           5624              321            ⋯
TACTGATGGATCAAAAACTGGCATAGGT         27027             9389            ⋯
TAAGAATCCTACTAACAGAAATCAAGACC         4406              391            ⋯
TGTAAGATCGAGAATTGACAAATGGGACC        12296             1285            ⋯

In [ ]:
hist(nchar(rownames(mircounts)))

In [22]:
#filter pirna from size 25 to 33

mircounts <- mircounts[nchar(rownames(mircounts)) ==27,]
dim(mircounts)

[1] 40802392       48

In [ ]:
setwd("/lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/analysis/seqCount/raw")
write.table(mircounts, file = "raw_count_matrix_16.5.5dpc.txt", sep = "\t",
            row.names = TRUE, col.names = TRUE)

In [ ]:
hist(nchar(rownames(mircounts)))

In [ ]:
#DESeq and PCA and Dandogram 


library("DESeq2")
library("gplots")
library("RColorBrewer")
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)

#save results in this folder 
setwd("/lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/analysis/seqCount/raw")

In [ ]:
# Make a color scheme for heatmaps
hmcol = colorRampPalette(brewer.pal(9, "GnBu"))(100)

In [ ]:
# First we tell DESeq which samples correspond to which tissues.

conds = data.frame(samplenames) ##what Desq2 manual calls coldata
colnames(conds)="sample"
samplenames

In [ ]:
# Now we build a DESeq2 Count dataset and normalize it.
library(BiocParallel)
register(MulticoreParam(3))
cds <- DESeqDataSetFromMatrix(countData = mircounts, colData = conds, design = ~ sample)
#cds <- estimateSizeFactors(cds)
#cds <- estimateDispersions(cds)
#cds <- nbinomWaldTest(cds)
cds <- DESeq(cds, parallel = TRUE)

In [ ]:
#rlog normalisations
#rlog() may take a long time with 50 or more samples,
#vst() is a much faster transformation
#rl=rlog(cds)

rl = vst(cds)

In [ ]:

pdf("BarGraphBeforeAfter_16.5dpc.pdf")
par(mfrow=c(2,1))

par(mar=c(10,10,0,10)) # increase y-axis margin.
prenorm=apply(mircounts,2,sum)
barplot(prenorm,col=as.factor(samplenames),las=2,names=samplenames,cex.names=0.8,space = 0.1)
postnorm=apply(counts(cds,normalized=TRUE),2,sum)
barplot(postnorm,col=as.factor(samplenames),las=2,names=samplenames,cex.names=0.8,space = 0.1)
dev.off()

In [ ]:
prenorm

In [ ]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], group = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "group", label = "name")) + geom_point(size = 3) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + coord_fixed()+ 
    theme_bw() + ggtitle(timePoint) 
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (timePoint in c("16.5")) {
print(timePoint)
rl.sub <- rl[ , rl$sample %in%  grep(paste0(timePoint), samplenames, value = TRUE) ]
pdf(paste0("PCA_After_1vs2_Beginning_",timePoint,".pdf"))
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = nrow(counts(cds))))
dev.off()
}

In [ ]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], group = group, 
                  intgroup.df, name = colData(rl)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "group", label = "name")) + geom_point(size = 3) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + coord_fixed()+ 
    theme_bw()+  theme(legend.text=element_text(size=5))
  
}

pdf("PCA_After_1vs2_Beginning_16.5dpc.pdf",paper="a4")
plotPCA.san(rl, intgroup = "sample", ntop = nrow(counts(cds)))
dev.off()

In [ ]:
##To plot PC1 versus 2 ## ALways change the colours to alphabetical order, and change the data.frame colData to rl.sub1 or approrpiate
plotPCA.san <- function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], group = group, 
                  intgroup.df, name = colData(rl.sub)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "group", label = "name")) + geom_point(size = 3) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + 
    ylab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + coord_fixed()+ 
    theme_bw() + ggtitle(strain) 
  
}


library(lattice)
strains <- unique(tools::file_path_sans_ext(sub("-[0-9]*", "", samplenames,perl = T)))

for (strain in strains) {
print(strain)
rl.sub <- rl[ , rl$sample %in%  grep(paste0("^",strain), samplenames, value = TRUE) ]
pdf(paste0("PCA_After_1vs2_Beginning_",strain,".pdf"))
print(plotPCA.san(rl.sub, intgroup = "sample", ntop = nrow(counts(cds))))
dev.off()
}

In [ ]:

##To plot PC2 versus 3
library(genefilter)
library(ggplot2)
library(ggrepel)

plotPCA.san <- function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC2 = pca$x[, 2], PC3 = pca$x[, 3], group = group, 
                  intgroup.df, name = colData(rl)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[2:3]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC2", y = "PC3", color = "group", label = "name")) + geom_point(size = 3) + xlab(paste0("PC2: ", round(percentVar[2] * 100), "% variance")) + ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed() 
  
}

pdf("PCA_After_3_16.5dpc.pdf",paper="a4")
plotPCA.san(rl, intgroup = 'sample', ntop = nrow(counts(cds)))
dev.off()

In [ ]:
##To plot PC1 versus 3
plotPCA.san <- function (object, intgroup = "condition", ntop = 500, returnData = FALSE) 
{
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC3 = pca$x[, 3], group = group, 
                  intgroup.df, name = colData(rl)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:3]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC3", color = "group", label = "name")) + geom_point(size = 3) + xlab(paste0("PC1: ", round(percentVar[1] * 100), "% variance")) + ylab(paste0("PC3: ", round(percentVar[3] * 100), "% variance")) + coord_fixed() 
  
}

pdf("PCA_After_4_16.5dpc.pdf",paper="a4")
plotPCA.san(rl, intgroup = 'sample', ntop = nrow(counts(cds)))
dev.off()

In [ ]:
####
# Margins area


pdf("InitialHeatMap_16.5dpc.pdf",title="Raw Seq Data",fillOddEven=T)
par(mar=c(0,0,0,0)) 
heatmap.2(cor(mircounts),trace="none",col=hmcol,main="Sample Correlation",cexRow=0.3,cexCol=0.3,key.title = 'Color Key',
    margins=c(10,10),na.rm=T,key=T, keysize = 1.5,offsetRow=0,offsetCol=0,density.info='histogram')
dev.off()

In [ ]:
##And the Spearman Dendogram
foo_sub_1 = counts(cds, normalized = TRUE)

foo_cor_1 = cor(foo_sub_1, method = "spearman") #builds matrix of Spearman corrn and euclidean distances

foo_cor_dist_1 = dist(foo_cor_1, method = "euclidean")
pdf(file="dendrogram_16.5dpc.pdf")
par( mar=c(5, 8, 4, 1))
plot(hclust(foo_cor_dist_1), cex = 0.6)
dev.off()

In [ ]:

##NEXT IS THE TOP 15% VARIANT miRNA plot on the means. Then the subset more useful miRNA plot
library(pheatmap)

foo_sub_1 <- as.data.frame.matrix(foo_sub_1) #convert from matrix to data frame
## use for eg foo$`hPGC_M_Wk9_n1` <- foo$`hPGC-M-Wk9_2` if only want one biol replicate

colnames(foo_sub_1)

head(foo_sub_1[ , grepl( "^129S1_SvImJ-12.5dpp" , names( foo_sub_1 ) ) ])
foo_sub1_mean = data.frame(matrix(NA, nrow = nrow(foo_sub_1), ncol = 0))
row.names(foo_sub1_mean) <- row.names(foo_sub_1)
for (sample in samplenames) {
foo_sub1_mean[sample] <- apply(foo_sub_1[ , grepl(paste0( "^",sample) , names( foo_sub_1 ) ) ], 1, mean)
}
head(foo_sub1_mean) 

foo_sub1_mean$sd_perGroup <- apply(foo_sub1_mean,1,sd)
hist(log1p(foo_sub1_mean$sd_perGroup),breaks = 200)


nrow(foo_sub1_mean)
3959
foo_sub1_mean_top15sd <- foo_sub1_mean[foo_sub1_mean$sd_perGroup>3959,1:16]
head(foo_sub1_mean_top15sd)
foo_sub1_mean_top15sd$ID<-rownames(foo_sub1_mean_top15sd)
head(foo_sub1_mean_top15sd)



save_pheatmap_pdf <- function(x, filename, width=15, height=25) {
    stopifnot(!missing(x))
    stopifnot(!missing(filename))
    pdf(filename, width=width, height=height,paper="special")
    grid::grid.newpage()
    grid::grid.draw(x$gtable)
    dev.off()
}

savePheatmap <- pheatmap(log1p(foo_sub1_mean_top15sd[,1:16]),width=28000,height=50000, border_color = NA,show_rownames = T, cluster_cols = T, labels_row = foo_sub1_mean_top15sd$ID,fontsize_row = 5, color = hmcol)

save_pheatmap_pdf(savePheatmap,"InitialPheatMap_16.5dpc.pdf")

In [ ]:

##for z-score
myCol = colorRampPalette(brewer.pal(9,"PRGn"))(100)


savePheatmapZScore <- pheatmap(foo_sub1_mean_top15sd[,1:16],,width=28000,height=50000, border_color = NA,show_rownames = T, cluster_cols = T,scale = "row",labels_row = foo_sub1_mean_top15sd$ID,fontsize_row = 5, color = myCol)

save_pheatmap_pdf(savePheatmapZScore,"InitialPheatMap_zScore_16.5dpc.pdf")